version: '3.9'
services:
  node:
    build:
      context: .
    image: node-binary
    volumes:
      - '.:/home/server'
    command: ["/bin/bash"]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    build: ./postgres
    image: postgres-db
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"